### ISSUE TITLE
Design QA: Modal Dialogs

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10167]
## Design QA punch list

- [ ] Why is this not available modal
- [ ] How to set up a new robot modal 
- [ ] Delete labware definition modal 
- [ ] Are you sure you want to calibrate modal
- [ ] Factory settings modal 
- [ ] Connection to robot lost modal 
- [ ] Software update modal 
- [ ] How to restore to a previous software version modal 
- [ ] Clear unavailable robots modal 
- [ ] Protocol analysis failure modal 
- [ ] Protocol failed its last analysis modal 
- [ ] Apply stored labware offset data modal (LPC Enhancements, #10146)
- [ ] Apply stored labware offset data super long modal (LPC Enhancements, #10146)
- [ ] Apply out of date stored labware offset data modal (LPC Enhancements, #10146)
- [ ] Robot is busy modal

**Comment by mmencarelli** [comment]
#10631 first round design qa on: 
- Why is this not available modal
- How to set up a new robot
- Delete this labware definition
- Factory settings modal
- Software Update Modal
- How to restore to a previous software version modal
