### ISSUE TITLE
6.0 Feedback: Design QA: T1 Protocols Landing Page #10153

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10208]
### Overview

Round 1 Feedback for Protocol Details page

### Current Behavior

n/a

### Expected Behavior

Link to view the annotated screenshot and side by side comparison to the intended design [on Figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11331%3A330817)

- [X] (1) Update styling of button to reflect our secondary style (no fill, update all states)
- [x] (2) Missing 'sort by' functionality
- [x] (3) Need 4px padding in between each card
- [X] (4) should be our p, semibold in dark-black #16212D
- [x] (5) should b our "link/secondary/grey/external" link styling which relies on our label font styling. Make sure to have all the states (currently missing them)
- [x] (6) center align the external svg icon and the text. Icon should be 12px, which is the same line height as the label text. 
- [x] (7) Need to align last updated text with design. Make sure it's follows the "styling/last-updated" style we have defined and in the correct location (fixed to the right hand side of the card)
- [x] (8) All text should be our dark-black #16212D, except for some the h6 headers, last updated date,  and links. 
- [x] (9) These h6's should be our dark-grey/enabled #707075, letter-spacing: 1%
- [x] (10) Can't figure out the flex box settings, but when the viewport is at 800px width, these columns should be able to hold the max number of characters without going onto two rows. (probably the "P1000 Single-Channel GEN2"). Not sure if it's because 'last updated' isn't tucked to the right? 
- [x] (11) The opened menu should be 4px below the menu overflow icon
- [x] (12) Menu overflow icon behavior [Loom video explaining](https://www.loom.com/share/3c49f4c275874210ae6dd2048a712d54)(please contact me if you have questions)
- [ ] (13) SVG adjustment. [Loom video explaining](https://www.loom.com/share/0c675ba03b80459f8c69db76e965e77b) (please contact me when you hit this, i think we'll need to work close together to solve)
- [x] (14) Update size of the spinner
- [x] (15) Update colour of the 'loading data...'
- [x] (16) Update to our h1 style, keeping it mind the colour should also be our 'dark-black'
- [x] (17) Update to our p style, make sure it's 'dark-black' colour
- [x] (18) Update to our primary button style 
- [x] (19) Update 'file_drop_zone' to our updated component in the design system 
- [x] (20) This entire section should be centered within the inner frame (see the original design to the left in Figma)
- [x] (21) should be the same amount of margin we have after the protocol cards when there's content (40px)

<img width="731" alt="Screen Shot 2022-05-04 at 12 02 59 PM" src="https://user-images.githubusercontent.com/54682054/166807449-127985ff-4e4a-476e-9c84-3121b0895180.png">
<img width="833" alt="Screen Shot 2022-05-04 at 2 41 49 PM" src="https://user-images.githubusercontent.com/54682054/166830501-667abfb6-9bc1-4a39-ae31-13fb6f94e71c.png">
