### ISSUE TITLE
Type-safe access to the HardwareControlAPI from Protocol API v2

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10700]
## Overview

This is an epic to collect various bits of tech debt / chore work required to introduce type-safe access to the `HardwareControlAPI` from Protocol API v2 interfaces. Currently, Hardware API access is:

- Not checked at all from `ProtocolContext` and `InstrumentContext`
- Half checked in `ModuleContext` interfaces (input values are checked, return values are not) 

It does this by was of introducing [`typing.ParamSpec`](https://docs.python.org/3/library/typing.html#typing.ParamSpec) into our Python codebase. `ParamSpec` will allow us to accurately type various bits higher-order-functions (e.g. function decorators) that are relatively common in our codebase and currently erase type signatures via `Any`.

Higher-order functions are used heavily in the Protocol API for cross-thread communications. In addition to improving the safety of our PAPIv2 code, this work will enable / unblock additional maintenance and bug fix work in PAPIv2 in general and move the needle on #9786 by simplifying the cross-thread structures that will eventually evolve into IPC.

## Acceptance criteria

- [ ] All access to the Hardware API from PAPIv2 is strictly type checked
- [ ] Can use `typing.ParamSpec` during type checks
- [ ] Usage of `typing.ParamSpec` does not introduce runtime errors
