### ISSUE TITLE
Calibration Dashboard: progress tracker

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10870]
# Overview

There needs to be a progress tracker added to the calibration dashboard.

# Implementation details

Loom download covering progress tracker logic here: https://www.loom.com/share/a24512581c4f42828f4a48b5a445ece5?t=225

Example of how the progress tracker should animate: https://ant.design/components/steps/

# Design

Detailed progress tracker designs are in the Design Systems folder: https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr/Design-System?node-id=2201%3A85193

Example of progress tracker going from complete calibration data to partial calibration data in the row below in this section of the designs: https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/6.2-Liquid-Setup%2C-Changing-Deck-State%2C-Wizards?node-id=2304%3A194016

# Acceptance criteria

- [ ] Progress tracker numbering logic renders correctly as steps are executed
- [ ] Step 1 active state renders correctly
- [ ] Step 1 completed, step 2A active state renders correctly 
- [ ] Step 2B active state renders correctly
- [ ] Step 1&2 completed, step 3 active state render correctly
- [ ] Step 1&2 completed, step 2 card open, step 3 active state renders correctly

**Comment by koji** [comment]
This was released as 6.3.
