### ISSUE TITLE
Labware should only displays either type or nickname; Labware change name functionality

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1281]
As a user, I would like to be able to see more of my wells in each labware. 

## Background
In the protocol designer, nickname and labware type seem to heavily overlap in purpose. We should only display one. 

### PART 1
- [x] Labware should only display either the nickname or the labware type.
- [x] Edit ingredients button on labware should become "edit details"

### PART 2
- [x] If a 96 Well Flat is being placed but a 96 Well Flat is already on the deck, this second plate's name defaults to "96 Well Flat (2)". Even if that first labware has a nickname. That way if the nickname is erased we never have instances where labware has identical names. 

### PART 3
- [ ] When you have labware open "Change Name" button should exist at the top of the sidebar. 
- [ ] Clicking "Change Name" button should open a change name form (illustrated below)
- [ ] When you clear the nickname field it defaults back to labware type.

## Design
![image](https://user-images.githubusercontent.com/35570080/39366764-dd9f1712-4a02-11e8-80ca-de31b97e375a.png)
![image](https://user-images.githubusercontent.com/35570080/40377545-2897bc7c-5dbf-11e8-8f2e-d1fe20520515.png)
