### ISSUE TITLE
Condense form fields in advanced settings

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1284]
As a user I would like to not be visually overwhelmed with form fields I don't intend to use. 

--

### Part 1
- [x] When checkboxes with attached for fields are unchecked, don't display those form fields. 
- [x] Turn change tip into a dropdown
- [x] Update 2nd column's fields to match the illustration (no well order, new placeholders for flow rate & tip position)
- [x] Optimize styles for smallest supported screen width

### Part 2 (TODO - break out into new separate ticket!)

- For now the advanced settings are in two columns: (1) Technique (2) Change tip, well order, flow rate.
- [ ] The two columns are evenly spaced initially, but then the 2nd moves right to accomodate changing width in column 1. 

## Design
![image](https://user-images.githubusercontent.com/35570080/39368704-4f4e4f0e-4a08-11e8-949f-b27272c786c8.png)
