### ISSUE TITLE
User Identification: Handle Magic Link in PD

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2934]
As a customer interested in using Protocol Designer, I would like a link to access PD and identify myself.

## prerequisites

- [ ] endpoint to send a magic link email to use (Opentrons/web-api#1, in review)
- [x] endpoint to verify token sent via magic link (Opentrons/web-api#2, done)
- [ ] endpoints reachable at Opentrons subdomain (Opentrons/web-api#10, in review)
- [ ] PD landing page with form to collect name and email (#2933)

## Acceptance Criteria

- [ ] On form submit, PD sends request to magic link endpoint
    - Exact `verifyUrl` TBD
    ```json
    {
        "email": "user@example.com",
        "name": "Super Scientist",
         "verifyUrl": "https://designer.opentrons.com/verify-email",
    }
    ```
- [ ] Upon navigation to `verifyUrl` (URL TBD), PD gets `?token` from URL and hits the verification endpoint
    ```json
    {
        "token": "token-from-query-param"
    }
    ```
- [ ] If verification endpoint responds with success, store name and email from response body in localStorage or cookie
- [ ] If verification endpoint response 401, inform user that token is likely expired, and let them try to resend the email
- [ ] If confirmation _or_ verification endpoint responds 400 or 5xx, display error message from server, which will be specific in the case of 400 (e.g. "email must be a valid email") or vague in the case of a 5xx (e.g. "gateway timeout")

**Comment by umbhau** [comment]
Replaced by #3149
