### ISSUE TITLE
Marketing Analytics: GTM tracking for Labware Library Navigation

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#3431]
## overview

As a Opentrons marketer, I would like to be able to use Google Tag Manager within the Labware Library.

## implementation details

- [ ] Add GTM script to labware library
- [ ] Add GTM tracking fields to navigation data
- [ ] Add GTM props to `website-navigation` components

## acceptance criteria

- [ ] All defined GTM actions track properly
