### ISSUE TITLE
feat(PD): Add data-test attributes for high priority elements in the File Tab

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5724]
# Overview

Writing stable and clean E2E tests means having sensible and unique selectors. Let's add `data-test` data attributes to elements on the File tab that currently have no good selectors but are needed for testing:

- [x] ~Create New Protocol Modal -> Pipette dropdown~ [#5791]
- [x] ~Create New Protocol Modal -> Pipette dropdown options~ [#5822]
- [x] ~Create New Protocol Modal -> Tiprack dropdowns~ [not necessary]
- [x] ~File Details -> Pipette Edit Button~ [#5826]
- [x] ~File Details -> Module Add Buttons~ [#5832]
- [x] ~File Details -> Module Edit Buttons~ [#5832]
- [x] ~File Details -> Module Remove Buttons~ [#5832]

Agreed upon naming convention for selectors:
**ComponentName_componentSelector**

See this [element list](https://docs.google.com/spreadsheets/d/1c6YKMnn0Wxdh4L56qcxsL0yVa0dDUqT4bFG2w2NKRgs/edit#gid=0) for more details
