### ISSUE TITLE
Switch front-end projects to yarn

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#576]
## overview

This ticket is a repo chore. Given that `npm` is _still_ causing problems, we're officially switching to [`yarn`](https://yarnpkg.com/en/) as package manager for our front-end projects. See #568 for the reasoning behind the switch.

Once the switch is made, using `npm` to develop will no longer be supported (apparently we had issues in the past with not picking and choosing one package manager).

## tasks

- [ ] Add `app`, `protocol-designer`, and `components` to the `workspaces` field in repo level `package.json`
    - https://yarnpkg.com/en/docs/workspaces
    - Update configs as necessary to handle `yarn`'s dependency linking
- [ ] Update common dependency versions to dedupe installs
- [ ] Remove old `package-lock.json`s in favor of single repo-level `yarn.lock`
- [ ] Update `Makefile`s to use `yarn` rather than `npm`
- [ ] Update `README.md` with `yarn` installation directions
- [ ] Update CI configuration as necessary to support `yarn`

**Comment by mcous** [comment]
*   Flow is not happy about yarn workspaces, and may require being pulled up to repo level as described in #578 
* Electron-builder is not playing nicely with workspaces because it can't resolve the hoisted dependencies
    *   Issue - https://github.com/electron-userland/electron-builder/issues/2222
    *   Possible workaround that's not yet ready: https://github.com/yarnpkg/yarn/issues/3882
    *   Possible solution: hacky, manual unhoisting of dependencies
    *   Possible solution: split app and app-shell and keep app-shell outside of `workspaces` for now

**Comment by mcous** [comment]
> `electron-builder` is not playing nicely with workspaces because it can't resolve the hoisted dependencies

I want to implement the last solution: split `app` into `app` and `app-shell`. I've been wanting to do this anyway, because:

* `app` has a unique directory structure compared to our other front-end projects, which increases cognitive switching costs
* The React app is written using `imports` which the Electron shell uses `require`
* Mixing app dependencies and desktop shell dependencies was confusing
    * React app is bundled, so its dependencies in `node_modules` don't need to be in the Electron package
    * With the combined directory, the only way to ensure sure this happens is to install React app dependencies as `devDependencies`, where they are mixed in with the desktop shell development dependencies
    * This is confusing and annoying and probably the primary reason I want to pull them apart anyway
* General separation of concerns
* Once `electron-builder` supports hoisted dependencies, `app-shell` can just become another yarn workspace

@Kadee80 or @IanLondon do you have any concerns with this approach? I've got a local branch with this in place and it works nicely. Going to consider this ticked **blocked** until the split happens.
