### ISSUE TITLE
Move NavBar and SidePanel components from App to Components

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#580]
## overview

This ticket is a **chore**

The [next iteration of the Protocol Designer](https://github.com/Opentrons/opentrons/milestone/2) requires the `Structure / Nav Bar` and `Structure / Side Panel` components in the library. These components already exist in the app, so we need to move them over to the components library.

This ticket blocks most of the other tickets in this milestone, so it should probably be tackled first.

## tasks

*   [ ] Copy NavBar to `components/src/structure`
*   [ ] Copy SidePanel to `components/src/structure`
    *    Ensure collapsibility is optional (app needs to be able to collapse it, PD does not)
*   [ ] Add any missing icons to `components/src/icons`
    *   Close X?
    *   Doc?
    *   Gear?
*   [ ] Update app to use components library NavBar and SidePanel
