### ISSUE TITLE
Allow app UI to function in web browser

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#5808]
## overview

We've been making good progress adding e2e tests to the Protocol Designer and Labware Library based on the [Cypress](https://www.cypress.io/) testing framework. Cypress runs in Chrome to test web UIs.

The Opentrons App runs on the [Electron framework](https://www.electronjs.org/), which means it has a "backend" in a Node.js process and a "frontend" in a Chromium process. If we were to somehow launch the UI in a full-on Chrome browser instead of the process launched via Electron, we could E2E test the app using Cypress.

## acceptance criteria

- [ ] UI can load and run in a web browser
- [ ] App can be run headlessly (without its Chromium UI)
- [ ] UI in a web-browser can communicate with the headless app

## implementation details

The app's Node.js process and Chromium UI process are already fairly decoupled at this point. The UI depends on the Node.js process for two main things:

- An [IPC message bus](https://www.electronjs.org/docs/api/ipc-main) to pass JSON packets back and forth between the "backend" and the "frontend"
- Initial seed data, namely:
    - Initial robots list
    - Current configuration file contents
    - Current version string and release notes

Theoretically, we could:

- Build an alternate message bus over WebSocket instead of IPC for the UI to use if it's launched in a browser
- Launch the Electron side of the app in headless mode where it spins up a WebSocket server instead of the IPC listener
    - For e2e testing the production app, a headless launch could also spin up a HTTP server to serve the production UI
- Stub out the initial seed data and/or move it to the message bus

**Comment by mcous** [comment]
Update: got a very light proof of concept going on this, and you can run the Electron app without a Chromium window and replace the IPC message bus with a WebSocket without much problem at all!

Aisde from the message bus, the remaining issues are purely architectural from an app UI state standpoint. I think the following changes are necessary:

- Allow app's `state.config` to be `null` (i.e. "unknown")
- Instead of pre-populating `state.config` with a direct value from the app-shell remote, have the app-shell send the config over upon `shell:INITIALIZE_UI`
- Abstract `ipc` logic in both `app` and `app-shell` into a more generic pair of message bus libraries that can act as simple facades for either Electron's IPC or a WebSocket
    - Ensure that the message bus module can recognize that its underlying transport is not yet ready and buffer outgoing messages on the `app` side
    - The `app-shell` side is already well-behaved and will not send any messages until it hears from the UI
    - Some sort of ping/pong keepalive in the case of a WS might be necessary

**Comment by mcous** [comment]
No longer pursuing this
