### ISSUE TITLE
Update TitledList to support PD step item

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#581]
## overview

To support the [step items in the Protocol Designer](https://github.com/Opentrons/opentrons/milestone/2), the TitledList component needs some updates.

![screenshot 2018-01-05 16 49 47](https://user-images.githubusercontent.com/2963448/34630051-7b75fafa-f238-11e7-8f91-125bb11b3cf0.png)

## tasks

*   [x] Add a selected prop
    *   Highlight on selection is common to both app and PD
*   [x] Add optional collapsed and onCollapseToggle props
    *   List needs to be able to collapse and expand (see screenshot)
*   [ ] Add optional string (or Node) description prop
    *   PD has "notes", app could definitely have descriptions
    *   Can't use children because children are placed inside an `<ol>`
*   [x] Remove non-`<li>` children from the `<ol>`
    *   Currently, we have other stuff in the `<ol>`
    *   This is invalid HTML
*   [x] Wire optional `onClick` prop to title click
*   [x] Ensure the TitledList renders properly without children
    *   Check padding, margins, etc.
    *   Also, hide collapse caret if there are no children (even if it should be collapsable)

**Comment by IanLondon** [comment]
The description isn't always just a string -- in PD it is styled text:

![image](https://user-images.githubusercontent.com/11590381/34682688-a775e502-f46d-11e7-82a3-d6144da43819.png)

So I'm thinking

```
<TitledList title='Title!' iconName={FLASK} selected
      description={<div><h4>Notes:</h4><em>These are the notes</em></div>} >
```

Which in real life PD would look more like:

```
<TitledList title={props.stepName} iconName={props.iconName} selected={props.selected}
      description={
          <div className={somePdStyles.step_notes}>
             <h1>Notes:</h1>
             <article>{props.notes}</article>
          </div>
      } >
```
