### ISSUE TITLE
Analytics: Add MixPanel Tracking Library to Protocol Designer

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#6057]
As a product manager, I would like to be able to analyze app usage in Protocol Designer, so that I can better understand feature use and adoption.

## Acceptance Criteria
- [ ] Add MixPanel library to Protocol Designer.
- [ ] Protocol Designer should be a part of the "Opentrons Web Apps" MixPanel project (alongside Labware Creator)
- [ ] MixPanel analytics should be turned on when users opt in to Protocol Designer session analytics (modal, and settings page toggle)
- [ ] MixPanel analytics should be turned off when users opt out of Protocol Designer session analytics (Settings page toggle)
- [ ] Add `appOpen` and `saveStep` event listed in "Protocol Designer" tab of the Event Tracking spreadsheet (see 'resources')

## Resources
[Event Tracking Plan](https://docs.google.com/spreadsheets/d/1pQxlZPcCg9PX6tmVBoDw36CLexKJ09rr7f2VdUSyyz0/edit#gid=813239919)
