### ISSUE TITLE
Plate component should display unrecognized labware types without throwing

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#616]
## overview

Currently, users have mechanisms through the existing protocol API through which they can add custom labware types to their robot / protocols. Attempting to use these protocols, however, blows up the app because the ~`Deck`~ `Plate` component cannot find the type key in `default-containers.json`.

## behavior

When attempting to calibrate labware with a protocol that uses a non-default labware, the app crashes to a white screen with an exception.

### 1. Create a new custom container 

Load this .py file into the app:

```python
import json
from os import path
from collections import OrderedDict

import opentrons
from opentrons.data_storage import database
from opentrons.data_storage.database_migration import rotate_container_for_alpha
from opentrons.data_storage.old_container_loading import create_container_obj_from_dict


containers_file = path.join(path.dirname(opentrons.__file__), 'config/containers/default-containers.json')

with open(containers_file) as f:
    containers = json.load(f, object_pairs_hook=OrderedDict)

new_name = 'tube-rack-5ml-96-beta-update'

database.delete_container(new_name)

wells = [
    (key, {**value, 'depth': 51})
    for key, value in containers['containers']['tube-rack-5ml-96']['locations'].items()]

containers['containers'][new_name] = {
    'locations': OrderedDict(wells)
}

database.save_new_container(rotate_container_for_alpha(
    create_container_obj_from_dict(containers['containers'][new_name])), new_name)
```

### 2. Run a protocol that uses that new container

```python
from opentrons import containers, instruments

tiprack200 = containers.load(
    'tiprack-200ul',  
    'A1',             
    'tiprack300'         
)

tuberack = containers.load(
    'tube-rack-5ml-96-beta-update',  
    'B2',             
    'tuberack'         
)

trash = containers.load(
	'fixed-trash',
	'C4',
	'trash'
)

p200 = instruments.Pipette(
    name="p300",
    trash_container=trash,
    tip_racks=[tiprack200],
    min_volume=30,
    max_volume=300,
    mount='right',
    channels=1,
    aspirate_speed=6,
    dispense_speed=10
)

p200.transfer(20, tuberack[0], tuberack[1])
```

## tasks

- [x] Update container library to import `default-containers.json` from path in `api` project
    - This is not a great inter-project dependency to have, but seeing as `default-containers.json` is going away:
    - This is better than having two files (one in API and one in PD) that could get out of sync
- [x] Have plate display some easy, sensible default for custom labware
    - We can worry about the "proper" solution once new labware definitions are locked down
- [x] Change `data-wellName` --> `data-wellname` to fix warning

**Comment by IanLondon** [comment]
+ Fix `data-wellName` as addressed in TODO:

> `TODO Ian 2017-12-13: should be lowercase data-wellname (Warning: React does not recognize the `data-wellName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-wellname` instead.)`

**Comment by IanLondon** [comment]
![image](https://user-images.githubusercontent.com/11590381/35123353-d7139aa2-fc6f-11e7-8548-b795678bdad6.png)
