### ISSUE TITLE
Remove Balena from Factory Provisioning

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6181]
## overview

The current OT-2 provisioning process relies on a convoluted process where devices are provisioned with Balena SD cards, updated via the app to a specific version (out of date) to run some tests that only work on that version, then updated again to another specific (and out of date) version to run some other tests, then shipped.

## key deliverables

The deliverables for this Epic are mostly SOP drafts to be shared with the hardware team for revisions and collaboration with the SZ.

- [x] [SD card provisioning SOP](https://github.com/Opentrons/opentrons/issues/6268)
    - Station setup (OS, installed software, etc.)
    - Robot OS files to use and how to get them
    - Instruction on how to flash the SD card
- [ ] Serial number provisioning SOP
    - Station setup (OS, installed software, etc.)
    - Instructions on how to write the serial number to the robot
    - See https://github.com/Opentrons/software-factory-scripts
- [x] Ensure current test scripts run on latest robot software
    - Test and modify scripts in `api/src/opentrons/tools` as necessary
    - This is a stopgap for replacing these scripts with a more concrete SOP and station
