### ISSUE TITLE
Connectivity: Authenticate to Known Wifi Networks

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#698]
As a user, I’d like to be able to authenticate to both known and wifi network

## Acceptance Criteria
- [x] User is able to see currently connected wifi network (PR #883)
- [x] User able to select a known network name and enter a password to connect a robot to a network (PR #898)
- [x] User shown dialogue box confirming failure/success (PR #914)
- Note: does not cover API failure response or app's failure handling logic (#694)
- Note: this story does not cover authenticating to unknown networks (#876)

## Design:
- Authenticate to known network: https://projects.invisionapp.com/share/V5FI4I26QWD#/screens/275374448
- Success dialogue:
https://projects.invisionapp.com/d/main#/console/13154070/275374450/preview

## Implementation Notes
- In the future, we may add additional fields to support authentication via additional auth protocols (e.g. providing a username). UI should be flexible enough to accommodate this down the road.
- This story is dependent on #807 (create a robot settings page)

**Comment by mcous** [comment]
Closed by #914
