### ISSUE TITLE
PD Basic Pipetting Steps: Consolidate (Step Form)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#732]
As a protocol designer, I’d like to be able to create a 'consolidate' step, so that I can easily move liquid from many location to one.

## Acceptance Criteria
- All fields created with FE validation
- Visual style updated to reflect mockup (below)
- User able to open 'more options' modal to see edit step name and notes
- User able to collapse or expand non-required field actions
- Note this US does not cover 'flow rate' or 'well selection'

### Fields
https://docs.google.com/document/d/16MAeEAHFO6lmMeNX4v4WEN4Aw5XiQYYQFhjUTHcMCQY/edit#
### Design
https://app.zeplin.io/project/5a2965f0cdd77b825fc7df24/screen/5a68eb4e18dd98839c86e1a4

#### More Options modal
![image](https://user-images.githubusercontent.com/11590381/35939313-c5262954-0c19-11e8-9ad4-c03447560303.png)

# TODO

- [x] All fields created with FE validation (can't save invalid form)
- [x] Visual style updated to reflect mockup (below)
- [x] User able to open 'more options' modal to see edit step name and notes (and fields can be saved)
- [x] User able to collapse or expand non-required field actions

**Comment by umbhau** [comment]
@howisthisnamenottakenyet 
Do we already have a mockup for the consolidate step? I loosely copied the above requirements from 'Distribute'

**Comment by IanLondon** [comment]
# TODO

- [x] All fields created with FE validation (can't save invalid form)
- [x] Visual style updated to reflect mockup (below)
- [ ] User able to open 'more options' modal to see edit step name and notes
- [ ] User able to collapse or expand non-required field actions
