### ISSUE TITLE
Protocol Engine milestone: Upload and run basic Python protocols

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#7844]
# User story

As a 3rd-party developer, I want to programmatically upload and run a basic Python APIv3 protocol on the OT-2.

# Acceptance criteria

* [ ] Using an HTTP API, I can upload a "basic" Python APIv3 protocol to the OT-2.
  * "Basic" means single-file, excluding modules, 8-Channel pipettes, and so on.
* [ ] Using an HTTP API, I can execute that protocol and make the robot move.
  * Execution must happen through Protocol Engine.
  * For the purposes of this story, we're going straight to execution. We don't care about calibration, metadata inspection, requirements inspection, or run log generation.
* [ ] If a protocol is already running, I'm disallowed from starting a new one.
	 * Bonus points: also don't let me start calibration or other stuff that would interfere.

We've punted running APIv2 protocols out of this sprint. For now, we can assume that all protocols coming through the new HTTP API are APIv3.

# Implementation suggestions

It could work like this (courtesy @sanni-t):

* An endpoint like `POST /protocols` takes the protocol file as form data.
* The robot-server, upon receiving the request with the file, sends the file to Python Protocol Runner, which may simulate and extract metadata (or these may be stubbed).
* Appropriate response to robot-server should include:
  * Metadata w/ Labware, modules, pipettes (empty fields)
  * Simulation result & warnings? (empty fields)
  * Handles to get:
    * Labware definitions
    * Protocol steps (Run log)
    * Create session
* A `create_session` endpoint uses the file runner to build (get?) protocol context and fetches the PE client to execute commands using PE. (File runner details in separate PR) 

See also #7647.
