### ISSUE TITLE
Robot Update: Dialogue Box & Initiate Update

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#813]
As a user, I would like to be given the option to update to the latest Robot server version.

## Acceptance Criteria
- 'Update' | 'Updated' link displayed in 'Information' card on 'Robot Settings' page
-- If current Robot version matches latest version, display inactive 'Updated' text
-- If current Robot version is behind latest version, display 'Update' link'
- Clicking button opens a robot update alert modal
-- Alert modal includes latest available server version number
-- Alert modal includes option to cancel ('not now') or 'update'
- Selecting 'Update' initiates a robot update

## Tasks (break down as stories?)
- [x] Add robot bundle to app shell (small) (#1027)
- [ ] Send robot bundle to api (robot server) (med) (#1051)
- [ ] UI including button, dialogue box, and confirmation (maybe confirmation is a separate story) (med)
    - #1055 
    - #1056
    - #1057
    - #1058

## Design
- https://projects.invisionapp.com/d/main#/console/13154070/275374445/preview

**Comment by btmorr** [comment]
API now supports update. See #912

**Comment by mcous** [comment]
UX review completed, feedback to be reviewed and addressed with additional tickets
