### ISSUE TITLE
Epic: Devices Landing Page

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8668]
# Overview

The Devices landing page is where the user lands after clicking on Devices in the main nav. This is where users can see which connected robots are available, set up a new robot's connection, and see the status and configuration of each robot in their lab. 

# Design
Robots landing designs in Figma: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A88551

# Acceptance criteria

- [ ] Empty state (no robots are connected)

- [ ] "Cards" for each connected robot with tooltip statuses for each connected module and a three-dot menu with a list of actions 

- [ ] The robots on this page should be broken into up to 3 sections for available, unavailable, and hidden robots (**Update**: Hidden robots are out of scope for 5.1)

- [ ] Modals for explaining why a robot is not available and why a robot might be missing from the landing page
